# Generated by Django 3.2.16 on 2023-05-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayer', '0003_auto_20230527_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicPlayer.song')),
            ],
        ),
    ]
